name: Auto Download Clash Rules

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时执行一次
  workflow_dispatch:       # 允许手动触发

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Prepare Directory
        run: mkdir -p Script/Clash

      - name: Download Clash Rules
        run: |
          cd Script/Clash

          declare -A RULES
          RULES["direct.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
          RULES["proxy.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
          RULES["reject.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
          RULES["private.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
          RULES["apple.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
          RULES["icloud.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
          RULES["google.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt"
          RULES["gfw.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt"
          RULES["tld-not-cn.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt"
          RULES["telegramcidr.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
          RULES["lancidr.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
          RULES["cncidr.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
          RULES["applications.txt"]="https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"

          for name in "${!RULES[@]}"; do
            echo "Downloading $name ..."
            curl -sSL "${RULES[$name]}" -o "$name"
          done

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add Script/Clash/*.txt
          git commit -m "🔄 Auto-update Clash rulesets" || echo "No changes to commit"
          git push

